vhost_manager_api:
    resource: "@VhostManagerApiBundle/Controller/"
    type:     annotation
    prefix:   /


users:
    type:   rest
    ressource:    VhostManager/ApiBundle/Controller/UsersController